##################
# Initialization #
##################
import pygame as pyg

FIELDLENGTH = 25
INFOWIDTH = 13
MAXROW = 100
MAXCOL = 15
MAXAMMO = 5
RED = (128, 0, 0)
GREEN = (0, 128, 0)
BLUE = (0, 0, 128)
WHITE = (255, 255, 255)
YELLOW = (128, 128, 0)
PURPLE = (128, 0, 128)
BLACK = (0, 0, 0)
COLORS = [RED, GREEN, BLUE, PURPLE, YELLOW]
LEFTSTICK = 0.7
BOTTOMSTICK = 0.5
CELLSIZE = 30
WIN_EVENT = pyg.USEREVENT + 1
ADD_AMMO_EVENT = pyg.USEREVENT + 2
AMMO_REPLENISH_SPEED = 1500
LOOSE_EVENT = pyg.USEREVENT + 3
MAIN_BLOB_SPEED = 80
MAIN_BLOB_MOVE_EVENT = pyg.USEREVENT + 4
# SMALL_BLOB_SPEED = 500
# SMALL_BLOB_MOVE_EVENT = pyg.USEREVENT + 5
FLASH_EVENT = pyg.USEREVENT + 6
TEXT_FLESH_TIME = 500
TIPS_EVENT = pyg.USEREVENT + 7
TIPS_TIME = 8000
GAME_FIELD = pyg.Rect(0, 0, MAXCOL*CELLSIZE, FIELDLENGTH*CELLSIZE)
INFO_FIELD = pyg.Rect((MAXCOL + 1) * CELLSIZE, 0, INFOWIDTH*CELLSIZE, FIELDLENGTH*CELLSIZE)
STARTGAME_TEXT = 'CLICK HERE or press SPACE'
pyg.font.init()